<%@ Page Title="" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="BookRegistration.aspx.cs" Inherits="Sarasavi.WebForm1" %>
<asp:Content ID="Content1" ContentPlaceHolderID="HeadContent" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="MainContent" runat="server">
    <!--Registration form starts here-->
    <body>
 <div  class = "registration">
<fieldset>
<legend>Book Registration</legend>
    <asp:Label ID="Label1" runat="server" Text="ISBN" ForeColor="White"></asp:Label>
    <br />
    <br />
    <asp:TextBox ID="txtISBN" runat="server" Height="30px" Width="373px"></asp:TextBox>
    <asp:RequiredFieldValidator ID="RequiredFieldValidator1" runat="server" 
        ControlToValidate="txtISBN" ErrorMessage="Please fill this field" 
        Font-Bold="False" ForeColor="#CC0000" ViewStateMode="Disabled"></asp:RequiredFieldValidator>
    <br />
    <br />
    <asp:Label ID="Label3" runat="server" Text="Book Title" ForeColor="White"></asp:Label>
    <br />
    <asp:TextBox ID="txtbookTtle" runat="server" Height="30px" Width="368px"></asp:TextBox>
    <asp:RequiredFieldValidator ID="RequiredFieldValidator2" runat="server" 
        ControlToValidate="txtbookTtle" ErrorMessage="Please fill this field" 
        Font-Bold="False" ForeColor="#CC0000" ViewStateMode="Disabled"></asp:RequiredFieldValidator>
    <br />
    <br />
    <asp:Label ID="Label10" runat="server" Text="Publisher" ForeColor="White"></asp:Label>
    <br />
    <asp:TextBox ID="txtPublisher" runat="server" Height="30px" Width="368px"></asp:TextBox>
    <asp:RequiredFieldValidator ID="RequiredFieldValidator3" runat="server" 
        ControlToValidate="txtPublisher" ErrorMessage="Please fill this field" 
        Font-Bold="False" ForeColor="#CC0000" ViewStateMode="Disabled"></asp:RequiredFieldValidator>
    <br />
    <br />
    <asp:Label ID="Label4" runat="server" Text="Author" ForeColor="White"></asp:Label>
    <br />
    <asp:TextBox ID="txtAuthor" runat="server" Height="30px" Width="368px"></asp:TextBox>
    <asp:RequiredFieldValidator ID="RequiredFieldValidator4" runat="server" 
        ControlToValidate="txtAuthor" ErrorMessage="Please fill this field" 
        Font-Bold="False" ForeColor="#CC0000" ViewStateMode="Disabled"></asp:RequiredFieldValidator>
    <br />
    <br />
    <asp:Label ID="Label5" runat="server" Text="Edition" ForeColor="White"></asp:Label>
    <br />
    <asp:TextBox ID="txtEdition" runat="server" Height="30px" Width="368px"></asp:TextBox>
    <asp:RequiredFieldValidator ID="RequiredFieldValidator5" runat="server" 
        ControlToValidate="txtEdition" ErrorMessage="Please fill this field" 
        Font-Bold="False" ForeColor="#CC0000" ViewStateMode="Disabled"></asp:RequiredFieldValidator>
    <br />
    <br />
    <asp:Label ID="Label6" runat="server" Text="Category" ForeColor="White"></asp:Label>
    <br />
    <asp:TextBox ID="txtCategory" runat="server" Height="30px" Width="368px"></asp:TextBox>
    <asp:RequiredFieldValidator ID="RequiredFieldValidator6" runat="server" 
        ControlToValidate="txtCategory" ErrorMessage="Please fill this field" 
        Font-Bold="False" ForeColor="#CC0000" ViewStateMode="Disabled"></asp:RequiredFieldValidator>
    <br />
    <br />
    <asp:Label ID="lblnumofCoppies" runat="server" ForeColor="White" 
        Text="Number of coppies"></asp:Label>
    <br />
    <asp:DropDownList ID="ddlnumofCopies" runat="server" Height="30px" Width="50px">
        <asp:ListItem>1</asp:ListItem>
        <asp:ListItem Value="2">2</asp:ListItem>
        <asp:ListItem Value="3">3</asp:ListItem>
        <asp:ListItem Value="4">4</asp:ListItem>
        <asp:ListItem Value="5">5</asp:ListItem>
        <asp:ListItem>6</asp:ListItem>
        <asp:ListItem Value="7">7</asp:ListItem>
        <asp:ListItem Value="8">8</asp:ListItem>
        <asp:ListItem>9</asp:ListItem>
        <asp:ListItem>10</asp:ListItem>
    </asp:DropDownList>
    <br />
    <br />
    <asp:Label ID="Label7" runat="server" Text="Copy_ISBN" ForeColor="White"></asp:Label><!--It might be an autogenerated one-->
    <br />
    <asp:TextBox ID="txtCopyISBN" runat="server" Height="30px" Width="368px"></asp:TextBox>
    <br />
    <br />
   
    <br />
    <asp:Button ID="Button1" runat="server" BackColor="#232B38" Height="57px" 
        Text="Register" Width="399px" BorderColor="#97704F" BorderStyle="Solid" 
        BorderWidth="4px" Font-Bold="True" Font-Size="18px" ForeColor="White" 
        onclick="Button1_Click" />
</fieldset>
</div>
</body>
</asp:Content>
